name:                web3-hexstring
version:             1.0.0.0
synopsis:            Hex-string type for Haskell Web3 library.
description:         Client library for Third Generation of Web.
github:              "airalab/hs-web3"
license:             Apache-2.0
license-file:        LICENSE
author:              Aleksandr Krupenkin
maintainer:          mail@akru.me
copyright:           "(c) Aleksandr Krupenkin 2016-2021"
category:            Network

dependencies:
- base                 >4.11 && <4.15
- text                 >1.2  && <1.3
- aeson                >1.2  && <1.6
- memory               >0.14 && <0.16
- bytestring           >0.10 && <0.11
- template-haskell     >2.11 && <2.17
- web3-scale           >=1.0 && <1.1

ghc-options:
- -funbox-strict-fields
- -Wduplicate-exports
- -Whi-shadowing
- -Widentities
- -Woverlapping-patterns
- -Wpartial-type-signatures
- -Wunrecognised-pragmas
- -Wtyped-holes
- -Wincomplete-patterns
- -Wincomplete-uni-patterns
- -Wmissing-fields
- -Wmissing-methods
- -Wmissing-exported-signatures
- -Wmissing-monadfail-instances
- -Wmissing-signatures
- -Wname-shadowing
- -Wunused-binds
- -Wunused-top-binds
- -Wunused-local-binds
- -Wunused-pattern-binds
- -Wunused-imports
- -Wunused-matches
- -Wunused-foralls
- -Wtabs

library:
  source-dirs: src
