# Resolver to choose a 'specific' stackage snapshot or a compiler version.
resolver: lts-9.2
# User packages to be built.
packages:
- '.'
# Dependency packages to be pulled from upstream that are not in the resolver
# (e.g., acme-missiles-0.3)
extra-deps: []
# Override default flag values for local packages and extra-deps
flags: {}
# Extra package databases containing global packages
extra-package-dbs: []
# Dependencies bounds
pvp-bounds: both
