# Resolver to choose a 'specific' stackage snapshot or a compiler version.
resolver: lts-24.32

# User packages to be built.
packages:
- 'packages/web3'
- 'packages/scale'
- 'packages/crypto'
- 'packages/bignum'
- 'packages/jsonrpc'
- 'packages/provider'
- 'packages/solidity'
- 'packages/ethereum'
- 'packages/polkadot'
- 'packages/hexstring'
- 'examples/erc20'
- 'examples/scale'
- 'examples/polkadot'

# Extra package dependencies
extra-deps:

# Dependencies bounds
pvp-bounds: both

# Nix integration
nix:
    packages:
    - haskellPackages.stylish-haskell
    - haskellPackages.hlint
    - zlib

flags:
  # bitvec C FFI causes unkown symbol error in windows build, disabling it
  bitvec:
    simd: false
