# Resolver to choose a 'specific' stackage snapshot or a compiler version.
resolver: lts-19.21

# User packages to be built.
packages:
- 'packages/web3'
- 'packages/ipfs'
- 'packages/scale'
- 'packages/crypto'
- 'packages/bignum'
- 'packages/jsonrpc'
- 'packages/provider'
- 'packages/solidity'
- 'packages/ethereum'
- 'packages/polkadot'
- 'packages/hexstring'
- 'examples/erc20'
- 'examples/scale'
- 'examples/polkadot'

# Extra package dependencies
extra-deps:
- animalcase-0.1.0.2@sha256:d7b80c3130c68d7ce8ddd9782588b2c4dd7da86461f302c54cc4acddf0902b51
- relapse-1.0.0.1

# Dependencies bounds
pvp-bounds: both

# Nix integration
nix:
    packages:
    - haskellPackages.stylish-haskell
    - haskellPackages.hlint
    - zlib
