name:                example-scale
version:             0.0.0.0
synopsis:            SCALE codec example.
github:              "airalab/hs-web3"
license:             Apache-2.0
author:              Aleksandr Krupenkin
maintainer:          mail@akru.me
copyright:           "(c) Aleksandr Krupenkin 2016-2020"
category:            Network

dependencies:
- base
- generics-sop
- web3-scale
- web3-hexstring

executables:
  example-scale:
    main:             Main.hs
    source-dirs:      ./
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
