name:                web3-ipfs
version:             1.0.0.1
synopsis:            IPFS support for Haskell Web3 library.
description:         Client library for Third Generation of Web.
github:              "airalab/hs-web3"
license:             Apache-2.0
license-file:        LICENSE
author:              Aleksandr Krupenkin
maintainer:          mail@akru.me
copyright:           "(c) Aleksandr Krupenkin 2016-2021"
category:            Network

dependencies:
- base                 >4.11 && <4.16
- mtl                  >2.2  && <2.3
- tar                  >0.4  && <0.6  
- text                 >1.2  && <1.3
- aeson                >1.2  && <2.1
- servant              >0.12 && <0.20
- http-media           >0.6  && <0.8.1
- bytestring           >0.10 && <0.11
- http-types           >0.11 && <0.14 
- http-client          >0.5  && <0.8
- servant-client       >0.12 && <0.20
- unordered-containers >0.1  && <0.3 

ghc-options:
- -funbox-strict-fields
- -Wduplicate-exports
- -Whi-shadowing
- -Widentities
- -Woverlapping-patterns
- -Wpartial-type-signatures
- -Wunrecognised-pragmas
- -Wtyped-holes
- -Wincomplete-patterns
- -Wincomplete-uni-patterns
- -Wmissing-fields
- -Wmissing-methods
- -Wmissing-exported-signatures
- -Wmissing-monadfail-instances
- -Wmissing-signatures
- -Wname-shadowing
- -Wunused-binds
- -Wunused-top-binds
- -Wunused-local-binds
- -Wunused-pattern-binds
- -Wunused-imports
- -Wunused-matches
- -Wunused-foralls
- -Wtabs

library:
  source-dirs: src
