name:                web3-provider
version:             1.0.0.0
synopsis:            Node connection provider for Haskell Web3 library.
description:         Client library for Third Generation of Web.
github:              "airalab/hs-web3"
license:             Apache-2.0
license-file:        LICENSE
author:              Aleksandr Krupenkin
maintainer:          mail@akru.me
copyright:           "(c) Aleksandr Krupenkin 2016-2020"
category:            Network

dependencies:
- base                 >4.11 && <4.15
- mtl                  >2.2  && <2.3
- text                 >1.2  && <1.3
- async                >2.1  && <2.3
- network              >2.5  && <3.2
- websockets           >0.10 && <0.13
- exceptions           >0.8  && <0.11
- http-client          >0.5  && <0.7
- data-default         >0.7  && <0.8
- transformers         >0.5  && <0.6
- web3-jsonrpc         >=1.0 && <1.1

ghc-options:
- -funbox-strict-fields
- -Wduplicate-exports
- -Whi-shadowing
- -Widentities
- -Woverlapping-patterns
- -Wpartial-type-signatures
- -Wunrecognised-pragmas
- -Wtyped-holes
- -Wincomplete-patterns
- -Wincomplete-uni-patterns
- -Wmissing-fields
- -Wmissing-methods
- -Wmissing-exported-signatures
- -Wmissing-monadfail-instances
- -Wmissing-signatures
- -Wname-shadowing
- -Wunused-binds
- -Wunused-top-binds
- -Wunused-local-binds
- -Wunused-pattern-binds
- -Wunused-imports
- -Wunused-matches
- -Wunused-foralls
- -Wtabs

library:
  source-dirs: src
