name:                web3-solidity
version:             1.0.0.0
synopsis:            Solidity language for Haskell Web3 library.
description:         Client library for Third Generation of Web.
github:              "airalab/hs-web3"
license:             Apache-2.0
license-file:        LICENSE
author:              Aleksandr Krupenkin
maintainer:          mail@akru.me
copyright:           "(c) Aleksandr Krupenkin 2016-2020"
category:            Network

dependencies:
- base                 >4.11 && <4.15
- text                 >1.2  && <1.3
- aeson                >1.2  && <1.6
- cereal               >0.5  && <0.6
- memory               >0.14 && <0.16
- tagged               >0.8  && <0.9
- parsec               >3.1  && <3.2
- basement             >0.0  && <0.1
- OneTuple             >0.2  && <0.3
- microlens            >0.4  && <0.5
- bytestring           >0.10 && <0.11
- generics-sop         >0.3  && <0.6
- data-default         >0.7  && <0.8
- template-haskell     >2.11 && <2.17
- web3-crypto          >=1.0 && <1.1
- web3-hexstring       >=1.0 && <1.1

ghc-options:
- -funbox-strict-fields
- -Wduplicate-exports
- -Whi-shadowing
- -Widentities
- -Woverlapping-patterns
- -Wpartial-type-signatures
- -Wunrecognised-pragmas
- -Wtyped-holes
- -Wincomplete-patterns
- -Wincomplete-uni-patterns
- -Wmissing-fields
- -Wmissing-methods
- -Wmissing-exported-signatures
- -Wmissing-monadfail-instances
- -Wmissing-signatures
- -Wname-shadowing
- -Wunused-binds
- -Wunused-top-binds
- -Wunused-local-binds
- -Wunused-pattern-binds
- -Wunused-imports
- -Wunused-matches
- -Wunused-foralls
- -Wtabs

library:
  source-dirs: src

tests:
  tests:
    main:             Spec.hs
    source-dirs:
    - tests 
    - src
    dependencies:
    - hspec-expectations   >=0.8.2  && <0.9
    - hspec-discover       >=2.4.4  && <2.8
    - hspec-contrib        >=0.4.0  && <0.6
    - hspec                >=2.4.4  && <2.8
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
