name:                web3-crypto
version:             1.0.0.1
synopsis:            Cryptograhical primitives for Haskell Web3 library.
description:         This package implements Web3 specific cryptography and helper functions.
github:              "airalab/hs-web3"
license:             Apache-2.0
license-file:        LICENSE
author:              Aleksandr Krupenkin
maintainer:          mail@akru.me
copyright:           "(c) Aleksandr Krupenkin 2016-2021"
category:            Network

extra-source-files:
- src/cbits/xxhash.h
- src/cbits/xxhash.c

dependencies:
- base                 >4.11  && <4.19
- text                 >1.2   && <2.1
- aeson                >1.2   && <2.2
- memory               >0.14  && <0.19
- vector               >0.12  && <0.14
- containers           >0.6   && <0.7
- uuid-types           >1.0   && <1.1
- crypton              >=0.31 && <1.0
- bytestring           >0.10  && <0.12
- memory-hexstring     >=1.0  && <1.1

ghc-options:
- -funbox-strict-fields
- -Wduplicate-exports
- -Whi-shadowing
- -Widentities
- -Woverlapping-patterns
- -Wpartial-type-signatures
- -Wunrecognised-pragmas
- -Wtyped-holes
- -Wincomplete-patterns
- -Wincomplete-uni-patterns
- -Wmissing-fields
- -Wmissing-methods
- -Wmissing-exported-signatures
- -Wmissing-monadfail-instances
- -Wmissing-signatures
- -Wname-shadowing
- -Wunused-binds
- -Wunused-top-binds
- -Wunused-local-binds
- -Wunused-pattern-binds
- -Wunused-imports
- -Wunused-matches
- -Wunused-foralls
- -Wtabs

library:
  source-dirs:  src
  include-dirs: src/cbits
  c-sources:    src/cbits/xxhash.c

tests:
  tests:
    main:             Spec.hs
    source-dirs:
    - tests
    - src
    include-dirs: src/cbits
    c-sources:    src/cbits/xxhash.c
    dependencies:
    - hspec-expectations   >=0.8.2  && <0.9
    - hspec-discover       >=2.4.4  && <2.12
    - hspec-contrib        >=0.4.0  && <0.6
    - hspec                >=2.4.4  && <2.12
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
